# Generated by Django 5.0.4 on 2024-04-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_metodospagos_usuarios_delete_clientes_pais_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodospagos',
            old_name='nombre',
            new_name='tarjeta',
        ),
        migrations.AlterField(
            model_name='metodospagos',
            name='cvv',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='metodospagos',
            name='numero_tarjeta',
            field=models.IntegerField(unique=True),
        ),
    ]
