# Generated by Django 5.0.4 on 2024-05-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_nombre_metodospagos_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodospagos',
            options={'verbose_name_plural': 'Metodos Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='metodospagos',
            name='tarjeta',
            field=models.CharField(max_length=150, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
    ]
