# Generated by Django 5.0.4 on 2024-05-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_metodospagos_titular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodospagos',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='metodospagos',
            name='numero_tarjeta',
        ),
        migrations.RemoveField(
            model_name='metodospagos',
            name='titular',
        ),
    ]
