# Generated by Django 5.0.4 on 2024-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_remove_metodospagos_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='email@email', max_length=254),
            preserve_default=False,
        ),
    ]
