# Generated by Django 5.0.4 on 2024-05-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_remove_usuarios_nacimiento_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tarjeta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.metodospagos'),
        ),
    ]
