# Generated by Django 5.0.4 on 2024-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_usuarios_tarjeta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
