# Generated by Django 5.0.4 on 2024-05-20 03:44

import cliente.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_usuarios_pais_origen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=cliente.models.CaseInsensitiveCharField(max_length=100, unique=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tarjeta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.metodospagos', verbose_name='Pago'),
        ),
    ]
