# Generated by Django 5.0.4 on 2024-05-20 03:49

import cliente.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_alter_pais_nombre_alter_usuarios_tarjeta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=cliente.models.CaseInsensitiveCharField(blank=True, max_length=100, unique=True, verbose_name='País'),
        ),
    ]
