# Generated by Django 5.0.4 on 2024-05-21 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_pais_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Última actualización'),
        ),
    ]
