# Generated by Django 5.0.4 on 2024-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_alter_usuarios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
