# Generated by Django 5.0.4 on 2024-05-21 02:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='codigo',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='precio_revista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=300),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='puntos',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='productocategoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
