# Generated by Django 5.0.4 on 2024-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productocategoria_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocategoria',
            name='codigo',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='código'),
        ),
    ]
