# Generated by Django 5.0.4 on 2024-05-21 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_productocategoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Última actualización'),
        ),
    ]
